name: Check templates
on:
  pull_request:
  push:
    branches: [main]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/checkout@v7
        with:
          repository: cubeshipd/cubeship
          ref: master
          path: _cubeship
      - uses: actions/setup-go@v7
        with:
          go-version-file: _cubeship/product/go.mod
          cache-dependency-path: _cubeship/product/go.sum
      - run: go run ./tools/templatecheck ../..
        working-directory: _cubeship/product
